In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import progressbar

In [2]:
cnter = 0
n_users = 99
bar = progressbar.ProgressBar(maxval=n_users+1, widgets=[progressbar.Bar('=', '[', ']'), ' ', progressbar.Percentage()])
bar.start()

[                                                                        ] N/A%

In [3]:
df = pd.DataFrame({
    "A": [1, 3] * 3,
    "B": ['a', 'b', np.nan, 'd', 'f', 20],
    "C": [np.nan, 10, np.nan, 14, 35, 'c'],
    "D": [12, 10, 2, 14, 35, 'c']
})

In [4]:
df

A    B    C   D
0  1    a  NaN  12
1  3    b   10  10
2  1  NaN  NaN   2
3  3    d   14  14
4  1    f   35  35
5  3   20    c   c

In [5]:
df.groupby(by=['A', 'B'])['C', 'D'].max()

C   D
A B          
1 a   NaN  12
  f    35  35
3 20    c   c
  b    10  10
  d    14  14

In [6]:

df.groupby(by=['A', 'B'])['C'].max().unstack()

B   20    a    b    d    f
A                         
1  NaN  NaN  NaN  NaN   35
3    c  NaN   10   14  NaN

In [7]:
df.pivot_table(values=['C', 'D'], index=['A'], columns=['B'], aggfunc=np.max)

C                   D                    
B   20    b    d    f   20    a    b    d    f
A                                             
1  NaN  NaN  NaN   35  NaN   12  NaN  NaN   35
3    c   10   14  NaN    c  NaN   10   14  NaN

In [8]:
cnter+=1 
bar.update(cnter)

In [9]:
A = np.array([10,4,6,7,1,5,3,24,9,10,18])
B = np.array([1,8,8,9])

In [10]:
A[np.in1d(A, B)]

array([1, 9])

In [11]:
np.intersect1d(A, B)

array([1, 9])

In [12]:
np.intersect1d(A, B, assume_unique=True)

array([ 1,  8,  9, 10])

In [13]:
np.setdiff1d(A, B, assume_unique=True)

array([10,  4,  6,  7,  5,  3, 24, 10, 18])

In [14]:
cnter+=1 
bar.update(cnter)

[=                                                                       ]   2%

In [15]:
s = 'Documentary|Short'
s.split('|')

['Documentary', 'Short']

In [16]:
s = pd.Series(['a_b_c_f_j', 'c_d_e_f_h', np.nan, 'f_g_h_x_g'])

In [17]:
s

0    a_b_c_f_j
1    c_d_e_f_h
2          NaN
3    f_g_h_x_g
dtype: object

In [18]:
s.str.split('_')

0    [a, b, c, f, j]
1    [c, d, e, f, h]
2                NaN
3    [f, g, h, x, g]
dtype: object

In [19]:
s.str.split('_', expand=True)

0    1    2    3    4
0    a    b    c    f    j
1    c    d    e    f    h
2  NaN  NaN  NaN  NaN  NaN
3    f    g    h    x    g

In [20]:
cnter+=1 
bar.update(cnter)

[==                                                                      ]   3%

In [21]:
a = np.array([2,4,6,8,10])

In [22]:
np.where(a > 5)

(array([2, 3, 4]),)

In [23]:
np.where(a > 5, 1, -1)

array([-1, -1,  1,  1,  1])

In [24]:
np.argwhere(a > 5)

array([[2],
       [3],
       [4]])

In [25]:
np.argmax(a)

4

In [26]:
np.argmin(a)

0

In [27]:
bar.finish()

[========================================================================] 100%
