In [71]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import progressbar

In [72]:
cnter = 0
n_users = 99
bar = progressbar.ProgressBar(maxval=n_users+1, widgets=[progressbar.Bar('=', '[', ']'), ' ', progressbar.Percentage()])
bar.start()

[                                                                        ] N/A%

In [73]:
df = pd.DataFrame({
    "A": [1, 3] * 3,
    "B": ['a', 'b', np.nan, 'd', 'f', 20],
    "C": [np.nan, 10, np.nan, 14, 35, 'c'],
    "D": [12, 10, 2, 14, 35, 'c'],
    "E": [2, 45, 68, np.nan, 35, np.nan]
})

In [74]:
df

A    B    C   D     E
0  1    a  NaN  12   2.0
1  3    b   10  10  45.0
2  1  NaN  NaN   2  68.0
3  3    d   14  14   NaN
4  1    f   35  35  35.0
5  3   20    c   c   NaN

In [75]:
df.groupby(by=['A', 'B'])['C', 'D'].max()

C   D
A B          
1 a   NaN  12
  f    35  35
3 20    c   c
  b    10  10
  d    14  14

In [76]:

df.groupby(by=['A', 'B'])['C'].max().unstack()

B   20    a    b    d    f
A                         
1  NaN  NaN  NaN  NaN   35
3    c  NaN   10   14  NaN

In [124]:
df.groupby(by=['A', 'B'])['C', 'D'].max().unstack()

C                        D                    
B   20    a    b    d    f   20    a    b    d    f
A                                                  
1  NaN  NaN  NaN  NaN   35  NaN   12  NaN  NaN   35
3    c  NaN   10   14  NaN    c  NaN   10   14  NaN

In [77]:
df.pivot_table(values=['C', 'D'], index=['A'], columns=['B'], aggfunc=np.max)

C                   D                    
B   20    b    d    f   20    a    b    d    f
A                                             
1  NaN  NaN  NaN   35  NaN   12  NaN  NaN   35
3    c   10   14  NaN    c  NaN   10   14  NaN

In [78]:
cnter+=1 
bar.update(cnter)

In [79]:
A = np.array([10,4,6,7,1,5,3,24,9,10,18])
B = np.array([1,8,8,9])

In [80]:
A[np.in1d(A, B)]

array([1, 9])

In [81]:
np.intersect1d(A, B)

array([1, 9])

In [82]:
np.intersect1d(A, B, assume_unique=True)

array([ 1,  8,  9, 10])

In [83]:
np.setdiff1d(A, B, assume_unique=True)

array([10,  4,  6,  7,  5,  3, 24, 10, 18])

In [84]:
cnter+=1 
bar.update(cnter)

[=                                                                       ]   2%

In [85]:
s = 'Documentary|Short'
s.split('|')

['Documentary', 'Short']

In [86]:
s = pd.Series(['a_b_c_f_j', 'c_d_e_f_h', np.nan, 'f_g_h_x_g'])

In [87]:
s

0    a_b_c_f_j
1    c_d_e_f_h
2          NaN
3    f_g_h_x_g
dtype: object

In [88]:
s.str.split('_')

0    [a, b, c, f, j]
1    [c, d, e, f, h]
2                NaN
3    [f, g, h, x, g]
dtype: object

In [89]:
s.str.split('_', expand=True)

0    1    2    3    4
0    a    b    c    f    j
1    c    d    e    f    h
2  NaN  NaN  NaN  NaN  NaN
3    f    g    h    x    g

In [90]:
cnter+=1 
bar.update(cnter)

[==                                                                      ]   3%

In [91]:
a = np.array([2,4,6,8,10])

In [92]:
np.where(a > 5)

(array([2, 3, 4]),)

In [93]:
np.where(a > 5, 1, -1)

array([-1, -1,  1,  1,  1])

In [94]:
np.argwhere(a > 5)

array([[2],
       [3],
       [4]])

In [95]:
np.argmax(a)

4

In [96]:
np.argmin(a)

0

In [97]:
s = [75.48556738,   9.67425201]

In [98]:
np.diag(s)

array([[75.48556738,  0.        ],
       [ 0.        ,  9.67425201]])

In [99]:
cnter+=1 
bar.update(cnter)

[==                                                                      ]   4%

In [100]:
np.array(df['C'])

array([nan, 10, nan, 14, 35, 'c'], dtype=object)

In [101]:
np.count_nonzero(~np.isnan(np.array(df['E'])))

4

In [102]:
cnter+=1 
bar.update(cnter)

In [103]:
a = np.array([[1,3,6],[9,5,6],[2,2,3]])

In [104]:
a

array([[1, 3, 6],
       [9, 5, 6],
       [2, 2, 3]])

In [105]:
np.matrix(a)

matrix([[1, 3, 6],
        [9, 5, 6],
        [2, 2, 3]])

In [106]:
a.argsort()

array([[0, 1, 2],
       [1, 2, 0],
       [0, 1, 2]])

In [107]:
a.argsort(axis=0)

array([[0, 2, 2],
       [2, 0, 0],
       [1, 1, 1]])

In [108]:
b = [1, 3, 6, 9, 5, 6, 2, 2, 3]

In [109]:
np.argsort(b)

array([0, 6, 7, 1, 8, 4, 2, 5, 3])

In [110]:
np.argsort(b)[::-1]

array([3, 5, 2, 4, 8, 1, 7, 6, 0])

In [111]:
cnter+=1 
bar.update(cnter)

[====                                                                    ]   6%

In [112]:
first = pd.DataFrame({'item_id':['a','b','c','b','d'],'item_price':[1,2,3,2,4]})
second = pd.DataFrame({'item_id':['a','b','f'],'item_atr':['k1','k2','k3']})

In [113]:
first, second

(  item_id  item_price
 0       a           1
 1       b           2
 2       c           3
 3       b           2
 4       d           4,
   item_id item_atr
 0       a       k1
 1       b       k2
 2       f       k3)

In [114]:
pd.concat([first, second])

item_atr item_id  item_price
0      NaN       a         1.0
1      NaN       b         2.0
2      NaN       c         3.0
3      NaN       b         2.0
4      NaN       d         4.0
0       k1       a         NaN
1       k2       b         NaN
2       k3       f         NaN

In [115]:
pd.concat([first, second], axis=1)

item_id  item_price item_id item_atr
0       a           1       a       k1
1       b           2       b       k2
2       c           3       f       k3
3       b           2     NaN      NaN
4       d           4     NaN      NaN

In [116]:
pd.concat([first, second], axis=0)

item_atr item_id  item_price
0      NaN       a         1.0
1      NaN       b         2.0
2      NaN       c         3.0
3      NaN       b         2.0
4      NaN       d         4.0
0       k1       a         NaN
1       k2       b         NaN
2       k3       f         NaN

In [117]:
first.join(second, lsuffix='_caller')

item_id_caller  item_price item_id item_atr
0              a           1       a       k1
1              b           2       b       k2
2              c           3       f       k3
3              b           2     NaN      NaN
4              d           4     NaN      NaN

In [118]:
second.set_index('item_id')

item_atr
item_id         
a             k1
b             k2
f             k3

In [119]:
first.join(second.set_index('item_id'), on='item_id')

item_id  item_price item_atr
0       a           1       k1
1       b           2       k2
2       c           3      NaN
3       b           2       k2
4       d           4      NaN

In [120]:
first.merge(second)

item_id  item_price item_atr
0       a           1       k1
1       b           2       k2
2       b           2       k2

In [121]:
pd.merge(first, second)

item_id  item_price item_atr
0       a           1       k1
1       b           2       k2
2       b           2       k2

In [122]:
cnter+=1 
bar.update(cnter)

[=====                                                                   ]   7%

In [123]:
bar.finish()

[========================================================================] 100%
