In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import progressbar

In [80]:
cnter = 0
n_users = 99
bar = progressbar.ProgressBar(maxval=n_users+1, widgets=[progressbar.Bar('=', '[', ']'), ' ', progressbar.Percentage()])
bar.start()

[                                                                        ] N/A%

In [81]:
df = pd.DataFrame({
    "A": [1, 3] * 3,
    "B": ['a', 'b', np.nan, 'd', 'f', 20],
    "C": [np.nan, 10, np.nan, 14, 35, 'c'],
    "D": [12, 10, 2, 14, 35, 'c'],
    "E": [2, 45, 68, np.nan, 35, np.nan]
})

In [82]:
df

A    B    C   D     E
0  1    a  NaN  12   2.0
1  3    b   10  10  45.0
2  1  NaN  NaN   2  68.0
3  3    d   14  14   NaN
4  1    f   35  35  35.0
5  3   20    c   c   NaN

In [83]:
df.groupby(['B'])['A'].value_counts().unstack()

A     1    3
B           
20  NaN  1.0
a   1.0  NaN
b   NaN  1.0
d   NaN  1.0
f   1.0  NaN

In [84]:
df.groupby(by=['A', 'B'])['C', 'D'].max()

C   D
A B          
1 a   NaN  12
  f    35  35
3 20    c   c
  b    10  10
  d    14  14

In [85]:

df.groupby(by=['A', 'B'])['C'].max().unstack()

B   20    a    b    d    f
A                         
1  NaN  NaN  NaN  NaN   35
3    c  NaN   10   14  NaN

In [86]:
df.groupby(by=['A', 'B'])['C', 'D'].max().unstack()

C                        D                    
B   20    a    b    d    f   20    a    b    d    f
A                                                  
1  NaN  NaN  NaN  NaN   35  NaN   12  NaN  NaN   35
3    c  NaN   10   14  NaN    c  NaN   10   14  NaN

In [87]:
df.pivot_table(values=['C', 'D'], index=['A'], columns=['B'], aggfunc=np.max)

C                   D                    
B   20    b    d    f   20    a    b    d    f
A                                             
1  NaN  NaN  NaN   35  NaN   12  NaN  NaN   35
3    c   10   14  NaN    c  NaN   10   14  NaN

In [88]:
cnter+=1 
bar.update(cnter)

In [89]:
A = np.array([10,4,6,7,1,5,3,24,9,10,18])
B = np.array([1,8,8,9])

In [90]:
A[np.in1d(A, B)]

array([1, 9])

In [91]:
np.intersect1d(A, B)

array([1, 9])

In [92]:
np.intersect1d(A, B, assume_unique=True)

array([ 1,  8,  9, 10])

In [93]:
np.setdiff1d(A, B, assume_unique=True)

array([10,  4,  6,  7,  5,  3, 24, 10, 18])

In [94]:
cnter+=1 
bar.update(cnter)

[=                                                                       ]   2%

In [95]:
s = 'Documentary|Short'
s.split('|')

['Documentary', 'Short']

In [96]:
s = pd.Series(['a_b_c_f_j', 'c_d_e_f_h', np.nan, 'f_g_h_x_g'])

In [97]:
s

0    a_b_c_f_j
1    c_d_e_f_h
2          NaN
3    f_g_h_x_g
dtype: object

In [98]:
s.str.split('_')

0    [a, b, c, f, j]
1    [c, d, e, f, h]
2                NaN
3    [f, g, h, x, g]
dtype: object

In [99]:
s.str.split('_', expand=True)

0    1    2    3    4
0    a    b    c    f    j
1    c    d    e    f    h
2  NaN  NaN  NaN  NaN  NaN
3    f    g    h    x    g

In [100]:
cnter+=1 
bar.update(cnter)

[==                                                                      ]   3%

In [101]:
a = np.array([2,4,6,8,10])

In [102]:
np.where(a > 5)

(array([2, 3, 4], dtype=int64),)

In [103]:
np.where(a > 5, 1, -1)

array([-1, -1,  1,  1,  1])

In [104]:
np.argwhere(a > 5)

array([[2],
       [3],
       [4]], dtype=int64)

In [105]:
np.argmax(a)

4

In [106]:
np.argmin(a)

0

In [107]:
s = [75.48556738,   9.67425201]

In [108]:
np.diag(s)

array([[75.48556738,  0.        ],
       [ 0.        ,  9.67425201]])

In [109]:
cnter+=1 
bar.update(cnter)

[==                                                                      ]   4%

In [110]:
np.array(df['C'])

array([nan, 10, nan, 14, 35, 'c'], dtype=object)

In [111]:
np.count_nonzero(~np.isnan(np.array(df['E'])))

4

In [112]:
cnter+=1 
bar.update(cnter)

In [113]:
a = np.array([[1,3,6],[9,5,6],[2,2,3]])

In [114]:
a

array([[1, 3, 6],
       [9, 5, 6],
       [2, 2, 3]])

In [115]:
np.matrix(a)

matrix([[1, 3, 6],
        [9, 5, 6],
        [2, 2, 3]])

In [116]:
a.argsort()

array([[0, 1, 2],
       [1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [117]:
a.argsort(axis=0)

array([[0, 2, 2],
       [2, 0, 0],
       [1, 1, 1]], dtype=int64)

In [118]:
b = [1, 3, 6, 9, 5, 6, 2, 2, 3]

In [119]:
np.argsort(b)

array([0, 6, 7, 1, 8, 4, 2, 5, 3], dtype=int64)

In [120]:
np.argsort(b)[::-1]

array([3, 5, 2, 4, 8, 1, 7, 6, 0], dtype=int64)

In [121]:
cnter+=1 
bar.update(cnter)

[====                                                                    ]   6%

In [122]:
first = pd.DataFrame({'item_id':['a','b','c','b','d'],'item_price':[1,2,3,2,4]})
second = pd.DataFrame({'item_id':['a','b','f'],'item_atr':['k1','k2','k3']})

In [123]:
first, second

(  item_id  item_price
 0       a           1
 1       b           2
 2       c           3
 3       b           2
 4       d           4,   item_id item_atr
 0       a       k1
 1       b       k2
 2       f       k3)

In [124]:
first.merge(second, on=['item_id'])

item_id  item_price item_atr
0       a           1       k1
1       b           2       k2
2       b           2       k2

In [125]:
first.merge(second, on=['item_id'], indicator=True)

item_id  item_price item_atr _merge
0       a           1       k1   both
1       b           2       k2   both
2       b           2       k2   both

In [126]:
pd.concat([first, second])

item_atr item_id  item_price
0      NaN       a         1.0
1      NaN       b         2.0
2      NaN       c         3.0
3      NaN       b         2.0
4      NaN       d         4.0
0       k1       a         NaN
1       k2       b         NaN
2       k3       f         NaN

In [127]:
pd.concat([first, second], axis=1)

item_id  item_price item_id item_atr
0       a           1       a       k1
1       b           2       b       k2
2       c           3       f       k3
3       b           2     NaN      NaN
4       d           4     NaN      NaN

In [128]:
pd.concat([first, second], axis=0)

item_atr item_id  item_price
0      NaN       a         1.0
1      NaN       b         2.0
2      NaN       c         3.0
3      NaN       b         2.0
4      NaN       d         4.0
0       k1       a         NaN
1       k2       b         NaN
2       k3       f         NaN

In [129]:
first.join(second, lsuffix='_caller')

item_id_caller  item_price item_id item_atr
0              a           1       a       k1
1              b           2       b       k2
2              c           3       f       k3
3              b           2     NaN      NaN
4              d           4     NaN      NaN

In [130]:
second.set_index('item_id')

item_atr
item_id         
a             k1
b             k2
f             k3

In [131]:
first.join(second.set_index('item_id'), on='item_id')

item_id  item_price item_atr
0       a           1       k1
1       b           2       k2
2       c           3      NaN
3       b           2       k2
4       d           4      NaN

In [132]:
first.merge(second)

item_id  item_price item_atr
0       a           1       k1
1       b           2       k2
2       b           2       k2

In [133]:
pd.merge(first, second)

item_id  item_price item_atr
0       a           1       k1
1       b           2       k2
2       b           2       k2

In [134]:
cnter+=1 
bar.update(cnter)

[=====                                                                   ]   7%

In [135]:
round(3.1415926, 3)

3.142

In [136]:
third = pd.DataFrame({
    'column1': [1, 3, 6, 8],
    'column2': ['one', 'two', 'three', 'four'],
    'column3': [{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9', 'reward': 5}, {'amount': 8}, {'offer_id': '2906b810c7d4411798c6938adc9daaa5'}, {'reward': 20}]
})

In [137]:
third.column3

0    {'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9...
1                                        {'amount': 8}
2     {'offer_id': '2906b810c7d4411798c6938adc9daaa5'}
3                                       {'reward': 20}
Name: column3, dtype: object

In [138]:
third.column3.apply(pd.Series)

offer id  reward  amount  \
0  9b98b8c7a33c4b65b9aebfe6a799e6d9     5.0     NaN   
1                               NaN     NaN     8.0   
2                               NaN     NaN     NaN   
3                               NaN    20.0     NaN   

                           offer_id  
0                               NaN  
1                               NaN  
2  2906b810c7d4411798c6938adc9daaa5  
3                               NaN

In [139]:
cnter+=1 
bar.update(cnter)

[=====                                                                   ]   8%

In [140]:
df = pd.DataFrame({"name": ["a","a","a","b","b","c"], "value": [1,2,3,4,5,6]})
df

name  value
0    a      1
1    a      2
2    a      3
3    b      4
4    b      5
5    c      6

In [141]:
df['value_shift_down'] = df.groupby('name')['value'].shift()
df

name  value  value_shift_down
0    a      1               NaN
1    a      2               1.0
2    a      3               2.0
3    b      4               NaN
4    b      5               4.0
5    c      6               NaN

In [142]:
df['value_shift_up'] = df.groupby('name')['value'].shift(-1)
df

name  value  value_shift_down  value_shift_up
0    a      1               NaN             2.0
1    a      2               1.0             3.0
2    a      3               2.0             NaN
3    b      4               NaN             5.0
4    b      5               4.0             NaN
5    c      6               NaN             NaN

In [143]:
cnter+=1 
bar.update(cnter)

[======                                                                  ]   9%

In [144]:
df = pd.DataFrame({
    "A": [1, 3] * 3,
    "B": ['a', 'b', np.nan, 'd', 'f', 20],
    "C": [np.nan, 10, np.nan, 14, 35, 'c'],
    "D": [12, 10, 2, 14, 35, 'c'],
    "E": [2, 45, 68, np.nan, 35, np.nan]
})
df

A    B    C   D     E
0  1    a  NaN  12   2.0
1  3    b   10  10  45.0
2  1  NaN  NaN   2  68.0
3  3    d   14  14   NaN
4  1    f   35  35  35.0
5  3   20    c   c   NaN

In [145]:
df.groupby(['A', 'B']).ffill()

C   D     E
0  NaN  12   2.0
1   10  10  45.0
2  NaN   2  68.0
3   14  14   NaN
4   35  35  35.0
5    c   c   NaN

In [146]:
df = pd.DataFrame([[1, 2], [3, 4]], columns=list('AB'))
df

A  B
0  1  2
1  3  4

In [147]:
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=list('AB'))
df2

A  B
0  5  6
1  7  8

In [148]:
df.append(df2)

A  B
0  1  2
1  3  4
0  5  6
1  7  8

In [149]:
cnter+=1 
bar.update(cnter)

In [150]:
df = pd.DataFrame({
    'a': [1, 2, 3, 4, 5, 6],
    'b': [1, 1, 2, 3, 5, 8],
    'c': [1, 4, 9, 16, 25, 36]
})
df

a  b   c
0  1  1   1
1  2  1   4
2  3  2   9
3  4  3  16
4  5  5  25
5  6  8  36

In [151]:
df.diff()

a    b     c
0  NaN  NaN   NaN
1  1.0  0.0   3.0
2  1.0  1.0   5.0
3  1.0  1.0   7.0
4  1.0  2.0   9.0
5  1.0  3.0  11.0

In [152]:
df_shift = df.shift(1)
df_shift

a    b     c
0  NaN  NaN   NaN
1  1.0  1.0   1.0
2  2.0  1.0   4.0
3  3.0  2.0   9.0
4  4.0  3.0  16.0
5  5.0  5.0  25.0

In [153]:
df - df_shift

a    b     c
0  NaN  NaN   NaN
1  1.0  0.0   3.0
2  1.0  1.0   5.0
3  1.0  1.0   7.0
4  1.0  2.0   9.0
5  1.0  3.0  11.0

In [154]:
cnter+=1 
bar.update(cnter)

[=======                                                                 ]  11%

In [155]:
first = pd.DataFrame({'item_id': ['a','b','c','b','d'], 'item_price': [1,2,3,2,4], 'item_tag': [5, 7, 3, 0, 4]})
second = pd.DataFrame({'item_id': ['a','b','f'], 'item_atr': ['k1','k2','k3'], 'item_price': [3, 2, 12]})

In [156]:
first

item_id  item_price  item_tag
0       a           1         5
1       b           2         7
2       c           3         3
3       b           2         0
4       d           4         4

In [157]:
second

item_id item_atr  item_price
0       a       k1           3
1       b       k2           2
2       f       k3          12

In [158]:
first.merge(second, how='left', on=['item_id', 'item_price'])

item_id  item_price  item_tag item_atr
0       a           1         5      NaN
1       b           2         7       k2
2       c           3         3      NaN
3       b           2         0       k2
4       d           4         4      NaN

In [159]:
first.merge(second, how='left', on=['item_id', 'item_price'], indicator=True)

item_id  item_price  item_tag item_atr     _merge
0       a           1         5      NaN  left_only
1       b           2         7       k2       both
2       c           3         3      NaN  left_only
3       b           2         0       k2       both
4       d           4         4      NaN  left_only

In [160]:
df = pd.DataFrame({
    'a': [1, 2, 3, 4, 5, 6],
    'b': [1, 1, 2, 3, 5, 8],
    'c': [1, 4, 9, 16, 25, 36]
})
df_first = df.iloc[0]
df_first

a    1
b    1
c    1
Name: 0, dtype: int64

In [161]:
df_a = df_first['a']
print(type(df_a))
df_b = df_first['b']
df_c = df_first['c']
d = dict(df_a=df_a, df_b=df_b, df_c=df_c)
d

<class 'numpy.int64'>


{'df_a': 1, 'df_b': 1, 'df_c': 1}

In [162]:
cnter+=1
bar.update(cnter)

[========                                                                ]  12%

In [163]:
letter = {}
# line = 'China is a Great Country'.upper()
line = input().upper()
for c in line:
    if c.isalpha():
        letter[c] = letter.get(c, 0) + 1
letterList = sorted(letter.items(), key=lambda x: x[1], reverse=True)

for t in letterList:
    print(t[0] + ':' + str(t[1]))

In [165]:
stud = []
item=['name', 'age', 'score']
while True:
    line = input()
    if not line:
        break
    else:
        xs = line.split()
        xs[1:] = map(int, xs[1:])
        stud.append(dict(zip(item, xs)))
temple = "Name:%(name)-10s Age:%(age)-5d Score:%(score)-5d"
for xs in stud:
    print(temple%xs)

已知a,b,c中存有1000以内被3,5,7整除的整数，试求1000以内 Q1：能被3且不能被5整除的数的个数，Q2：能被3和5整除但不能被7整除的数的个数，Q3：能被3或5整除，且同时能被7整除的数的个数。

In [178]:
a = {i for i in range(0, 1000, 3)}
b = {i for i in range(0, 1000, 5)}
c = {i for i in range(0, 1000, 7)}
print("Q1:" + str(len([x for x in a - b])))
print("Q2:" + str(len([x for x in a & b - c])))
print("Q3:" + str(len([x for x in (a | b) & c])))

Q1:267
Q2:57
Q3:67


In [167]:
cnter+=1
bar.update(cnter)

[=========                                                               ]  13%

In [168]:
bar.finish()

[========================================================================] 100%
