In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [14]:
df = pd.DataFrame({
    "A": [1, 3] * 3,
    "B": ['a', 'b', np.nan, 'd', 'f', 20],
    "C": [np.nan, 10, np.nan, 14, 35, 'c']
})

In [15]:
df

A    B    C
0  1    a  NaN
1  3    b   10
2  1  NaN  NaN
3  3    d   14
4  1    f   35
5  3   20    c

In [17]:
tmp_set = set()

In [18]:
tmp_set.add('123')
tmp_set

{'123'}

In [19]:
tmp_set.update('123')
tmp_set

{'1', '123', '2', '3'}

In [20]:
tmp_set.update(['abc'])
tmp_set

{'1', '123', '2', '3', 'abc'}

In [21]:
a = np.array([1,2,3])
b = np.array([11,22,33])
c = np.array([44,55,66])

In [24]:
concate_result = np.concatenate((a, b, c))
concate_result

array([ 1,  2,  3, 11, 22, 33, 44, 55, 66])

In [25]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[11,21,31],[7,8,9]])

In [27]:
two_dimension_concate_result_0 = np.concatenate((a,b), axis=0)
two_dimension_concate_result_0

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 21, 31],
       [ 7,  8,  9]])

In [28]:
two_dimension_concate_result_1 = np.concatenate((a,b), axis=1)
two_dimension_concate_result_1

array([[ 1,  2,  3, 11, 21, 31],
       [ 4,  5,  6,  7,  8,  9]])

In [22]:
np.concatenate?

Docstring:
concatenate((a1, a2, ...), axis=0, out=None)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.

Returns
-------
res : ndarray
    The concatenated array.

See Also
--------
ma.concatenate : Concatenate function that preserves input masks.
array_split : Split an array into multiple sub-arrays of equal or
              near-equal size.
split : Split array into a list of multiple sub-arrays of equal size.
hsplit : Split array into multiple sub-arrays horizontally 