In [130]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import progressbar

In [131]:
cnter = 0
n_users = 99
bar = progressbar.ProgressBar(maxval=n_users+1, widgets=[progressbar.Bar('=', '[', ']'), ' ', progressbar.Percentage()])
bar.start()

[                                                                        ] N/A%

In [132]:
df = pd.DataFrame({
    "A": [1, 3] * 3,
    "B": ['a', 'b', np.nan, 'd', 'f', 20],
    "C": [np.nan, 10, np.nan, 14, 35, 'c'],
    "D": [12, 10, 2, 14, 35, 'c'],
    "E": [2, 45, 68, np.nan, 35, np.nan]
})

In [133]:
df

A    B    C   D     E
0  1    a  NaN  12   2.0
1  3    b   10  10  45.0
2  1  NaN  NaN   2  68.0
3  3    d   14  14   NaN
4  1    f   35  35  35.0
5  3   20    c   c   NaN

In [134]:
df.groupby(['B'])['A'].value_counts().unstack()

A     1    3
B           
20  NaN  1.0
a   1.0  NaN
b   NaN  1.0
d   NaN  1.0
f   1.0  NaN

In [135]:
df.groupby(by=['A', 'B'])['C', 'D'].max()

C   D
A B          
1 a   NaN  12
  f    35  35
3 20    c   c
  b    10  10
  d    14  14

In [136]:

df.groupby(by=['A', 'B'])['C'].max().unstack()

B   20    a    b    d    f
A                         
1  NaN  NaN  NaN  NaN   35
3    c  NaN   10   14  NaN

In [137]:
df.groupby(by=['A', 'B'])['C', 'D'].max().unstack()

C                        D                    
B   20    a    b    d    f   20    a    b    d    f
A                                                  
1  NaN  NaN  NaN  NaN   35  NaN   12  NaN  NaN   35
3    c  NaN   10   14  NaN    c  NaN   10   14  NaN

In [138]:
df.pivot_table(values=['C', 'D'], index=['A'], columns=['B'], aggfunc=np.max)

C                   D                    
B   20    b    d    f   20    a    b    d    f
A                                             
1  NaN  NaN  NaN   35  NaN   12  NaN  NaN   35
3    c   10   14  NaN    c  NaN   10   14  NaN

In [139]:
cnter+=1 
bar.update(cnter)

In [140]:
A = np.array([10,4,6,7,1,5,3,24,9,10,18])
B = np.array([1,8,8,9])

In [141]:
A[np.in1d(A, B)]

array([1, 9])

In [142]:
np.intersect1d(A, B)

array([1, 9])

In [143]:
np.intersect1d(A, B, assume_unique=True)

array([ 1,  8,  9, 10])

In [144]:
np.setdiff1d(A, B, assume_unique=True)

array([10,  4,  6,  7,  5,  3, 24, 10, 18])

In [145]:
cnter+=1 
bar.update(cnter)

[=                                                                       ]   2%

In [146]:
s = 'Documentary|Short'
s.split('|')

['Documentary', 'Short']

In [147]:
s = pd.Series(['a_b_c_f_j', 'c_d_e_f_h', np.nan, 'f_g_h_x_g'])

In [148]:
s

0    a_b_c_f_j
1    c_d_e_f_h
2          NaN
3    f_g_h_x_g
dtype: object

In [149]:
s.str.split('_')

0    [a, b, c, f, j]
1    [c, d, e, f, h]
2                NaN
3    [f, g, h, x, g]
dtype: object

In [150]:
s.str.split('_', expand=True)

0    1    2    3    4
0    a    b    c    f    j
1    c    d    e    f    h
2  NaN  NaN  NaN  NaN  NaN
3    f    g    h    x    g

In [151]:
cnter+=1 
bar.update(cnter)

[==                                                                      ]   3%

In [152]:
a = np.array([2,4,6,8,10])

In [153]:
np.where(a > 5)

(array([2, 3, 4]),)

In [154]:
np.where(a > 5, 1, -1)

array([-1, -1,  1,  1,  1])

In [155]:
np.argwhere(a > 5)

array([[2],
       [3],
       [4]])

In [156]:
np.argmax(a)

4

In [157]:
np.argmin(a)

0

In [158]:
s = [75.48556738,   9.67425201]

In [159]:
np.diag(s)

array([[75.48556738,  0.        ],
       [ 0.        ,  9.67425201]])

In [160]:
cnter+=1 
bar.update(cnter)

[==                                                                      ]   4%

In [161]:
np.array(df['C'])

array([nan, 10, nan, 14, 35, 'c'], dtype=object)

In [162]:
np.count_nonzero(~np.isnan(np.array(df['E'])))

4

In [163]:
cnter+=1 
bar.update(cnter)

In [164]:
a = np.array([[1,3,6],[9,5,6],[2,2,3]])

In [165]:
a

array([[1, 3, 6],
       [9, 5, 6],
       [2, 2, 3]])

In [166]:
np.matrix(a)

matrix([[1, 3, 6],
        [9, 5, 6],
        [2, 2, 3]])

In [167]:
a.argsort()

array([[0, 1, 2],
       [1, 2, 0],
       [0, 1, 2]])

In [168]:
a.argsort(axis=0)

array([[0, 2, 2],
       [2, 0, 0],
       [1, 1, 1]])

In [169]:
b = [1, 3, 6, 9, 5, 6, 2, 2, 3]

In [170]:
np.argsort(b)

array([0, 6, 7, 1, 8, 4, 2, 5, 3])

In [171]:
np.argsort(b)[::-1]

array([3, 5, 2, 4, 8, 1, 7, 6, 0])

In [172]:
cnter+=1 
bar.update(cnter)

[====                                                                    ]   6%

In [173]:
first = pd.DataFrame({'item_id':['a','b','c','b','d'],'item_price':[1,2,3,2,4]})
second = pd.DataFrame({'item_id':['a','b','f'],'item_atr':['k1','k2','k3']})

In [174]:
first, second

(  item_id  item_price
 0       a           1
 1       b           2
 2       c           3
 3       b           2
 4       d           4,
   item_id item_atr
 0       a       k1
 1       b       k2
 2       f       k3)

In [175]:
pd.concat([first, second])

item_atr item_id  item_price
0      NaN       a         1.0
1      NaN       b         2.0
2      NaN       c         3.0
3      NaN       b         2.0
4      NaN       d         4.0
0       k1       a         NaN
1       k2       b         NaN
2       k3       f         NaN

In [176]:
pd.concat([first, second], axis=1)

item_id  item_price item_id item_atr
0       a           1       a       k1
1       b           2       b       k2
2       c           3       f       k3
3       b           2     NaN      NaN
4       d           4     NaN      NaN

In [177]:
pd.concat([first, second], axis=0)

item_atr item_id  item_price
0      NaN       a         1.0
1      NaN       b         2.0
2      NaN       c         3.0
3      NaN       b         2.0
4      NaN       d         4.0
0       k1       a         NaN
1       k2       b         NaN
2       k3       f         NaN

In [178]:
first.join(second, lsuffix='_caller')

item_id_caller  item_price item_id item_atr
0              a           1       a       k1
1              b           2       b       k2
2              c           3       f       k3
3              b           2     NaN      NaN
4              d           4     NaN      NaN

In [179]:
second.set_index('item_id')

item_atr
item_id         
a             k1
b             k2
f             k3

In [180]:
first.join(second.set_index('item_id'), on='item_id')

item_id  item_price item_atr
0       a           1       k1
1       b           2       k2
2       c           3      NaN
3       b           2       k2
4       d           4      NaN

In [181]:
first.merge(second)

item_id  item_price item_atr
0       a           1       k1
1       b           2       k2
2       b           2       k2

In [182]:
pd.merge(first, second)

item_id  item_price item_atr
0       a           1       k1
1       b           2       k2
2       b           2       k2

In [183]:
cnter+=1 
bar.update(cnter)

[=====                                                                   ]   7%

In [184]:
round(3.1415926, 3)

3.142

In [185]:
third = pd.DataFrame({
    'column1': [1, 3, 6, 8],
    'column2': ['one', 'two', 'three', 'four'],
    'column3': [{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9', 'reward': 5}, {'amount': 8}, {'offer_id': '2906b810c7d4411798c6938adc9daaa5'}, {'reward': 20}]
})

In [186]:
third.column3

0    {'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9...
1                                        {'amount': 8}
2     {'offer_id': '2906b810c7d4411798c6938adc9daaa5'}
3                                       {'reward': 20}
Name: column3, dtype: object

In [187]:
third.column3.apply(pd.Series)

offer id  reward  amount  \
0  9b98b8c7a33c4b65b9aebfe6a799e6d9     5.0     NaN   
1                               NaN     NaN     8.0   
2                               NaN     NaN     NaN   
3                               NaN    20.0     NaN   

                           offer_id  
0                               NaN  
1                               NaN  
2  2906b810c7d4411798c6938adc9daaa5  
3                               NaN

In [188]:
cnter+=1 
bar.update(cnter)

[=====                                                                   ]   8%

In [189]:
bar.finish()

[========================================================================] 100%
